apps/DjangoUeditor/urls.py
#coding:utf-8
from django import VERSION
if VERSION[0:2]>(1,3):
    from django.conf.urls import patterns, url
else:
    from django.conf.urls.defaults import patterns, url

from views import get_ueditor_controller

urlpatterns = patterns('',
    url(r'^controller/$',get_ueditor_controller)
)

mrfinger/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from articles.views import ArticleView, ArticleDetailView, ArticleListView, AboutView, RSSView
from mrfinger.settings import STATIC_ROOT, MEDIA_ROOT
import xadmin
from django.views.static import serve

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$',ArticleView.as_view(), name="index"),
    url(r'^archives/',ArticleListView.as_view(), name="archives"),
    url(r'^detail/(?P<article_id>\d+)/$',ArticleDetailView.as_view(), name="detail"),
    url(r'^about/',AboutView.as_view(), name="about"),
    url('^rss/', RSSView.as_view(), name="rss"),
    # url('^rss/', AboutView.as_view(), name="rss"),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]


handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_not_found'

apps/articles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from DjangoUeditor.models import UEditorField
# Create your models here.

class Tag(models.Model):
    tag_name = models.CharField(max_length=64)
    def __unicode__(self):
        return self.tag_name

    class Meta:
        verbose_name = u'标签'
        verbose_name_plural = verbose_name


class Article(models.Model):
    title = models.CharField(max_length = 150)  # 博客题目
    category = models.CharField(max_length = 50, blank = True)  #博客分类 可为空
    tag = models.ForeignKey(Tag, blank=True, default='')  # 博客标签 可为空
    date_time = models.DateTimeField(auto_now_add = True)  #博客日期
    click_number = models.IntegerField(default=0, verbose_name=u"点击数")
    year = models.IntegerField(default=int(datetime.now().year), verbose_name=u'年份')
    # content = models.TextField(blank = True, null = True)  #博客文章正文
    content = UEditorField(verbose_name=u'博客==内容', width=900, height=500, imagePath="ueditor/",
                          filePath="ueditor/",blank=True, default="")


    class Meta:
        verbose_name = u'文章'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return '{0}(类别： {1})'.format(self.title, self.tag)


class About(models.Model):
    about = UEditorField(verbose_name=u'关于', width=900, height=500, imagePath="ueditor/",
                         filePath="ueditor/", blank=True, default="")
    date_time = models.DateTimeField(verbose_name=u'更新日期', default=datetime.now)  # 更改日期

    class Meta:
        verbose_name = u"关于"
        verbose_name_plural = verbose_name

 

extra_apps/xadmin/views/base.py
import sys
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.utils.encoding import force_unicode, force_text
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_unicode, smart_unicode, smart_str
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, basestring) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_unicode(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        for r in remove:
            for k in p.keys():
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

    def init_request(self, *args, **kwargs):
        pass

    def init_plugin(self, *args, **kwargs):
        plugins = []
        for p in self.base_plugins:
            p.request = self.request

templates/about.html
{% extends 'base.html' %}
{% block main %}
    <main class="container">
        <div class="post">
            <article class="post-block">
{#                <h1 class="post-title">{{ article.title }}</h1>#}
                <div class="post-info">{{ about.date_time|date:"Y-m-d H:i:s" }}</div>
                <div class="post-content">
                    {% autoescape on %}
                        {{ about.about | safe }}
                    {% endautoescape %}
                </div>
            </article>
        </div>
    </main>
{% endblock %}

templates/archives.html
{% extends 'base.html' %}
{% block main %}
    <main class="container">
        <div class="archive">
            <h2 class="archive-year">2017</h2>
            {% for article in article_list %}
                <div class="post-item">
                    <div class="post-info">{{ article.date_time|date:"Y-m-d" }}</div>
                    <a href="{% url 'detail' article.id %}" class="post-title-link">{{ article.title }}</a></div>
            {% endfor %}
        </div>
    </main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="utf-8">
    <meta name="X-UA-Compatible" content="IE=edge">
    <title> ヾ(=ﾟ･ﾟ=)ﾉ喵♪~Mr.Finger</title>
    <meta name="description" content="C++ Developer, Gopher, Pythoner, love open source.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/pic/favicon.png">
    <link rel="stylesheet" href="/static/css/apollo.css">
    <link rel="search" type="application/opensearchdescription+xml" href="http://andrewliu.in/atom.xml"
          title="ヾ(=ﾟ･ﾟ=)ﾉ喵♪~Mr.Finger">
    {% block custom_style %}
    {% endblock %}
</head>
<body>
<div class="wrap">
    <header>
        <a href="/" class="logo-link"><img src="/static/pic/favicon.png" alt="logo"></a>
        <ul class="nav nav-list">
            <li class="nav-list-item"><a href="/" target="_self" class="nav-list-link {% ifequal flag 'index' %}active{% endifequal %}">天天吹牛</a>
            </li>
            <li class="nav-list-item"><a href="/archives/" target="_self" class="nav-list-link {% ifequal flag 'list' %}active{% endifequal %}">整理</a></li>
            <li class="nav-list-item"><a href="http://weibo.com/u/2494046041" target="_blank"
                                         class="nav-list-link">非官方吐槽</a></li>
            <li class="nav-list-item"><a href="https://github.com/zhentoufei" target="_blank" class="nav-list-link">给她哈不</a>
            </li>
            <li class="nav-list-item"><a href="/about/" target="_self" class="nav-list-link {% ifequal flag 'about' %}active{% endifequal %}">关于</a></li>
            <li class="nav-list-item"><a href="/rss/" target="_self" class="nav-list-link {% ifequal flag 'rss' %}active{% endifequal %}">RSS</a></li>
        </ul>
    </header>
    {% block main %}

    {% endblock %}
    <footer>
        {% block footer_page %}
        {% endblock %}
        <div class="copyright"><p>@❤🍁❤👉  <a href="">Mr.Finger</a>, powered by <a
                href="#" target="_blank">Mr.Finger</a>  <a
                href="http://www.miitbeian.gov.cn" target="_blank"> 备...备案：苏ICP备17043699号-1</a></p></div>
    </footer>
</div>

</body>
</html>

templates/detail.html
{% extends 'base.html' %}
{% block main %}
    <main class="container">
        <div class="post">
            <article class="post-block"><h1 class="post-title">{{ article.title }}</h1>
                <div class="post-info">{{ article.date_time|date:"Y-m-d H:i:s" }}</div>
                <div class="post-content">
                    {% autoescape on %}
                        {{ article.content | safe }}
                    {% endautoescape %}
                </div>
            </article>
        </div>
    </main>
{% endblock %}

templates/error404.html
{% extends 'base.html' %}
{% block main %}

    <h2 style="text-align: center; margin-top: 10%">欢迎做客</h2>
    <div class="error">
        <a style="font-size: 60px;text-align: center">404</a>
        <a style="font-size: 60px;text-align: center;transform:rotate(-30deg);">嘿嘿嘿</a></div>

{% endblock %}
{% block custom_style %}
    <style>
        div.error {
            margin: auto auto;
            margin-bottom: 260px;
            width: 200px;
            height: 100px;
            /* Rotate div */
            transform: rotate(9deg);
            -ms-transform: rotate(9deg); /* Internet Explorer */
            -moz-transform: rotate(9deg); /* Firefox */
            -webkit-transform: rotate(9deg); /* Safari 和 Chrome */
            -o-transform: rotate(9deg); /* Opera */
        }
    </style>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block main %}
    <main class="container">
        <ul class="home post-list">
            {% for article in all_article %}

                <li class="post-list-item">
                    <article class="post-block">
                        <h1 class="post-title"><a href="{% url 'detail' article.id %}"
                                                  class="post-title-link">{{ article.title }}</a></h1>
                        <div class="post-info">{{ article.date_time|date:"Y-m-d H:i:s" }}</div>
                        <div class="post-content">
                            {% autoescape on %}
                                {{ article.content | safe | truncatewords_html:30 }}
                            {% endautoescape %}
                        </div>
                        <a href="{% url 'detail' article.id %}" class="read-more">......阅读全文</a></article>
                </li>
            {% endfor %}

        </ul>
    </main>
{% endblock %}
{% block footer_page %}
{#    <div class="paginator"><a href="/page/2/" class="next">下一页</a></div>#}
{% endblock %}

templates/rss.html
{% extends 'base.html' %}
{% block main %}
    <div>
        <P style="font-size: 30px;font-style: italic;text-align: center;margin-bottom: 180px;margin-top: 120px;">
            博主正在缓慢开发中.....可能是有生之年系列</P>
    </div>
{% endblock %}